version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mlflow_db
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mlflow:
    build:
      context: .
    environment:
      BACKEND_STORE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/mlflow_db
      ARTIFACT_STORE: s3://us-energy-price-forecasting/artifacts/
      MODEL_REGISTRY_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/mlflow_db
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ap-southeast-1
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    command:
      - sh    # (sh allows for var substitution of BACKEND and ARTIFACTS)
      - -c
      - mlflow server 
        --port 5000
        --host 0.0.0.0 
        --backend-store-uri $${BACKEND_STORE_URI} 
        --default-artifact-root $${ARTIFACT_STORE}
        --registry-store-uri $${MODEL_REGISTRY_URI}

volumes:
  pgdata:


