FROM apache/airflow:2.7.0-python3.10

USER root

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

ADD requirements.txt .

RUN pip install --no-cache-dir \
 --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.7.0/constraints-3.10.txt" \
 -r requirements.txt